### ISSUE TITLE
Additional list

### ISSUE THREAD

**Issue by lidarbtc** [clementvial/official-swag#7]
- [path.net](https://merch.path.net/)
- [metamask](https://metamask.myspreadshop.com/)
- [equinix metal](https://shop.equinixmetal.com/)
- [equinix](https://store.equinix.com/)
- [solana](https://store.solana.com/)
- [golang](https://store.ardanlabs.com/)
- [signal](https://shop.signal.org/)
- [slack](https://salesforcestore.com/slack/)
- [proton](https://shop.proton.me/)

**Comment by lidarbtc** [comment]
- [solidjs](https://www.solidjs.com/store)

**Comment by clementvial** [comment]
This issue has been resolved with commit 564772e.
